spring.application.name=JWA-SS12-HW4
server.port=8081
server.servlet.context-path=/api/v1

#Spring Boot quản lý các cấu hình mặc định thông qua cơ chế Auto-configuration kết hợp với hệ thống
# Default Properties được định nghĩa sẵn bên trong framework.
#
#Cụ thể, khi ứng dụng khởi động, Spring Boot sẽ tự động cấu hình các thành phần dựa trên:
#
#Các dependency có trong project (ví dụ: Web, JPA, Security…)
#Các giá trị mặc định đã được định nghĩa sẵn
#
#Nếu lập trình viên không khai báo gì thêm, Spring Boot sẽ sử dụng các giá trị mặc định này để ứng dụng
# vẫn có thể chạy bình thường. Ví dụ như:
#
#Cổng mặc định là 8080
#Context path mặc định là /
#
#Ngoài ra, Spring Boot cho phép ghi đè (override) các cấu hình mặc định này thông qua file application.properties
# hoặc application.yml.
#
#Danh sách đầy đủ các cấu hình mặc định có thể được tìm thấy trong tài liệu chính thức của Spring Boot, cụ thể là
# phần Common Application Properties. Đây là nơi liệt kê tất cả các key cấu hình mà lập trình viên có thể sử dụng
# để tùy chỉnh ứng dụng.